// ============================================================
// ISHAMI SIMULATION — Low Poly City Scenarios
// 6 new beginner scenarios using the low_poly_city model
// Waypoints adjusted to match actual road layout:
//   Main road: x=[-25,5], z=[-7,0]
//   Side roads: at x positions, z=[-7,0]
// ============================================================

import type { ScenarioConfig } from './AllScenarios';

// ─── Scenario 1: Start & Move 5 Meters ─────────────────────

export const LOWPOLY_START_AND_GO: ScenarioConfig = {
  id: 'lowpoly_start_go',
  title: 'Start & Move Forward',
  titleRW: 'Tangira Ujye Imbere',
  description: 'The very first lesson: start your engine, select first gear, and drive forward 5 meters. You can do it!',
  descriptionRW: 'Igitangira: tangira injini, hitamo igeari ya mbere, kandi ujye imbere metero 5.',
  difficulty: 'BEGINNER',
  location: 'Low Poly City — Main Road Start',
  locationRW: 'Low Poly City — Umuhanda wa Tangira',
  estimatedTime: '1-2 min',
  maxSpeed: 20,
  speedLimit: 15,
  xpReward: 150,
  trainingMode: true,
  objectives: [
    { id: 'start_engine', text: 'Start the engine', textRW: 'Tangira injini', icon: '🔑' },
    { id: 'first_gear', text: 'Select first gear', textRW: 'Hitamo igeari ya mbere', icon: '⚙️' },
    { id: 'move_forward', text: 'Drive forward 5 meters', textRW: 'Jya imbere metero 5', icon: '🚗' },
    { id: 'stop', text: 'Come to a complete stop', textRW: 'Hagarika neza', icon: '🛑' },
  ],
  waypoints: [
    {
      id: 'SG_START',
      position: [-20, 0, -3.5],
      radius: 4,
      objective: 'Starting position — engine off',
      instruction: 'You are parked on the main road. Start your engine first.',
      completed: false,
      instructorMessage: 'Welcome! This is your very first driving lesson. Start the engine — clutch in, key turn!',
    },
    {
      id: 'SG_GEAR',
      position: [-20, 0, -7],
      radius: 3,
      objective: 'Select first gear',
      instruction: 'Clutch in, select first gear, release handbrake gently.',
      completed: false,
      instructorMessage: 'Clutch in! Select first gear (1). Release the handbrake. Ready to move!',
    },
    {
      id: 'SG_HALF',
      position: [-15, 0, -7],
      radius: 4,
      objective: 'Halfway — keep going!',
      instruction: 'Great start! Keep the steering straight and maintain gentle throttle.',
      completed: false,
      instructorMessage: 'You are moving! Keep it steady. Steering straight. Almost there!',
    },
    {
      id: 'SG_FINISH',
      position: [-10, 0, -7],
      radius: 4,
      objective: 'Stop here — 5 meters driven!',
      instruction: 'Brake gently and come to a complete stop. You did it!',
      completed: false,
      instructorMessage: 'PERFECT! You started the engine, drove forward, and stopped safely. Mission complete!',
    },
  ],
};

// ─── Scenario 2: Traffic Flow ──────────────────────────────
// Drive through the city respecting traffic lights, zebra crossings, and animated pedestrians

export const LOWPOLY_TRAFFIC_FLOW: ScenarioConfig = {
  id: 'lowpoly_traffic_flow',
  title: 'Traffic Flow',
  titleRW: 'Kugendagenda',
  description: 'Navigate through traffic lights and zebra crossings. Stop for pedestrians and respect every red light.',
  descriptionRW: 'Gukemura mu myubahirirane y\'amatara y\'umuhanda. Hagarika kubera abanyamaguru.',
  difficulty: 'BEGINNER',
  location: 'Low Poly City — Central Intersection',
  locationRW: 'Low Poly City — Inkomane y\'Umujyi',
  estimatedTime: '3-5 min',
  maxSpeed: 30,
  speedLimit: 25,
  xpReward: 250,
  trainingMode: true,
  objectives: [
    { id: 'obey_lights', text: 'Obey all traffic lights', textRW: 'Kurikiza amatara yose', icon: '🚦' },
    { id: 'zebra_stop', text: 'Stop at zebra crossings', textRW: 'Hagarika ku zebra', icon: '🚶' },
    { id: 'yield_ped', text: 'Yield to pedestrians', textRW: 'Tega abanyamaguru', icon: '👥' },
    { id: 'stay_lane', text: 'Stay in your lane', textRW: 'Guma mu imbanza yawe', icon: '🛣️' },
    { id: 'safe_speed', text: 'Maintain safe speed', textRW: 'Kurikiza umuvuduko', icon: '⚡' },
  ],
  trafficLights: [
    { position: [-10, 0, -3], rotation: 0 },
    { position: [-10, 0, -7], rotation: Math.PI },
    { position: [0, 0, -3], rotation: 0 },
  ],
  aiVehicles: [
    {
      position: [-15, 0, -3.5],
      color: 0xcc3333,
      speed: 6,
      path: [[-15, 0, -3.5], [-5, 0, -3.5], [5, 0, -3.5], [5, 0, -7], [-5, 0, -7], [-15, 0, -7], [-15, 0, -3.5]],
    },
    {
      position: [-20, 0, -7],
      color: 0x3366cc,
      speed: 4,
      path: [[-20, 0, -7], [-10, 0, -7], [0, 0, -7], [0, 0, -3.5], [-10, 0, -3.5], [-20, 0, -3.5], [-20, 0, -7]],
    },
  ],
  pedestrians: [
    { position: [-10, 0, -5], path: [[-10, 0, -5], [-10, 0, -2]], speed: 1.2 },
    { position: [0, 0, -5], path: [[0, 0, -5], [0, 0, -2]], speed: 1.0 },
  ],
  waypoints: [
    {
      id: 'TF_START',
      position: [-22, 0, -3.5],
      radius: 4,
      objective: 'Start driving on the main road',
      instruction: 'Begin driving on the main road. Watch for traffic lights ahead.',
      completed: false,
      instructorMessage: 'Off you go! Drive carefully. First traffic light is coming up.',
    },
    {
      id: 'TF_LIGHT_1',
      position: [-12, 0, -3.5],
      radius: 3,
      objective: 'Obey first traffic light',
      instruction: 'Traffic light ahead! Stop if red, proceed if green.',
      completed: false,
      instructorMessage: 'Traffic light! Check the color. Red = STOP. Green = GO carefully.',
    },
    {
      id: 'TF_ZEBRA',
      position: [-10, 0, -5],
      radius: 3,
      objective: 'Stop at zebra crossing',
      instruction: 'Zebra crossing with pedestrians! Stop completely and let them cross.',
      completed: false,
      instructorMessage: 'ZEBRA CROSSING! Stop NOW. Pedestrians have priority. Wait until clear.',
    },
    {
      id: 'TF_LIGHT_2',
      position: [-2, 0, -3.5],
      radius: 3,
      objective: 'Navigate second traffic light',
      instruction: 'Second intersection. Check traffic light before proceeding.',
      completed: false,
      instructorMessage: 'Intersection ahead! Check light, check mirrors, then decide.',
    },
    {
      id: 'TF_TURN',
      position: [3, 0, -3.5],
      radius: 3,
      objective: 'Turn right at intersection',
      instruction: 'Signal right and make a smooth turn at the intersection.',
      completed: false,
      instructorMessage: 'Signal right! Check mirrors and blind spot. Turn smoothly.',
    },
    {
      id: 'TF_ZEBRA_2',
      position: [3, 0, -5.5],
      radius: 3,
      objective: 'Stop at second zebra crossing',
      instruction: 'Another zebra crossing! Stop and wait for pedestrians.',
      completed: false,
      instructorMessage: 'Another zebra! Stop. Wait. Pedestrians first, always.',
    },
    {
      id: 'TF_FINISH',
      position: [-5, 0, -7],
      radius: 4,
      objective: 'Mission complete!',
      instruction: 'You completed the traffic flow course. Well done!',
      completed: false,
      instructorMessage: 'Excellent! You obeyed traffic lights and let pedestrians cross. Perfect driving!',
    },
  ],
};

// ─── Scenario 3: Corners & Turns ───────────────────────────

export const LOWPOLY_CORNERS_TURNS: ScenarioConfig = {
  id: 'lowpoly_corners_turns',
  title: 'Corners & Turns',
  titleRW: 'Imfuruka',
  description: 'Navigate corners and turns through the city while staying on the road and using indicators.',
  descriptionRW: 'Kukemura imfuruka mu mujyi ukurikiza imbanza.',
  difficulty: 'BEGINNER',
  location: 'Low Poly City — Residential Streets',
  locationRW: 'Low Poly City — Imiryango y\'Abatuye',
  estimatedTime: '3-5 min',
  maxSpeed: 25,
  speedLimit: 20,
  xpReward: 200,
  trainingMode: true,
  objectives: [
    { id: 'signal_turns', text: 'Signal at every turn', textRW: 'Oreza buri furuka', icon: '🔄' },
    { id: 'stay_road', text: 'Stay within road lines', textRW: 'Guma mu imbanza', icon: '🛣️' },
    { id: 'slow_turn', text: 'Slow down before turns', textRW: 'Guma cyangwa mbere yo furuka', icon: '🐢' },
    { id: 'check_mirrors', text: 'Check mirrors before each turn', textRW: 'Reba amadaruro', icon: '🪞' },
  ],
  waypoints: [
    {
      id: 'CT_START',
      position: [-22, 0, -3.5],
      radius: 4,
      objective: 'Start the turning course',
      instruction: 'Begin driving straight. A series of turns is coming up.',
      completed: false,
      instructorMessage: 'Welcome to the turning course! First turn is coming. Signal early!',
    },
    {
      id: 'CT_TURN_1',
      position: [-15, 0, -3.5],
      radius: 3,
      objective: 'Sharp right turn',
      instruction: 'Slow down and make a right turn. Stay within the road.',
      completed: false,
      instructorMessage: 'Sharp right! Slow down, signal right, check mirrors, then turn!',
    },
    {
      id: 'CT_TURN_2',
      position: [-15, 0, -7],
      radius: 3,
      objective: 'Left turn at corner',
      instruction: 'Turn left at this corner. Use indicator and stay in lane.',
      completed: false,
      instructorMessage: 'Left turn now! Signal left. Remember: slow in, fast out!',
    },
    {
      id: 'CT_STRAIGHT',
      position: [-5, 0, -7],
      radius: 4,
      objective: 'Straight section — keep steady',
      instruction: 'Drive straight through this section. Maintain steady speed.',
      completed: false,
      instructorMessage: 'Straight section. Good. Steady speed. Watch for the next turn.',
    },
    {
      id: 'CT_TURN_3',
      position: [3, 0, -7],
      radius: 3,
      objective: 'Right turn at T-junction',
      instruction: 'T-junction ahead! Signal right and turn onto the side road.',
      completed: false,
      instructorMessage: 'T-junction! Signal right, check BOTH ways, then turn when safe.',
    },
    {
      id: 'CT_TURN_4',
      position: [3, 0, -3.5],
      radius: 3,
      objective: 'U-turn — change direction',
      instruction: 'Make a safe U-turn when the road is clear. Signal both directions.',
      completed: false,
      instructorMessage: 'U-Turn! Check ALL directions. Signal left then right. Turn carefully!',
    },
    {
      id: 'CT_FINISH',
      position: [-5, 0, -3.5],
      radius: 4,
      objective: 'Turn course complete!',
      instruction: 'Stop here. You completed all turns successfully!',
      completed: false,
      instructorMessage: 'Great turning skills! You signaled, slowed down, and stayed in lane. Perfect!',
    },
  ],
};

// ─── Scenario 4: Reverse & Backup Driving ──────────────────

export const LOWPOLY_REVERSE_DRIVING: ScenarioConfig = {
  id: 'lowpoly_reverse_driving',
  title: 'Reverse & Backup',
  titleRW: 'Gutwara Inyuma',
  description: 'Practice reversing in a straight line and turning corners while reversing. Remember: steering is reversed!',
  descriptionRW: 'Jya mu gihe usubira inyuma. Menya: steering ihinduka!',
  difficulty: 'BEGINNER',
  location: 'Low Poly City — Parking Zone',
  locationRW: 'Low Poly City — Ahantu h\'Imodoka',
  estimatedTime: '3-5 min',
  maxSpeed: 10,
  speedLimit: 8,
  xpReward: 250,
  trainingMode: true,
  objectives: [
    { id: 'gear_reverse', text: 'Select reverse gear (R)', textRW: 'Hitamo gear y\'inyuma', icon: '⚙️' },
    { id: 'straight_reverse', text: 'Reverse in a straight line', textRW: 'Subira inyuma mu buriri', icon: '↩️' },
    { id: 'check_behind', text: 'Check behind constantly', textRW: 'Reba inyuma', icon: '👀' },
    { id: 'reverse_turn', text: 'Reverse around a corner', textRW: 'Subira inyuma mu furuka', icon: '🔄' },
    { id: 'stop_reverse', text: 'Stop precisely at the target', textRW: 'Hagarika neza', icon: '🎯' },
  ],
  waypoints: [
    {
      id: 'RV_START',
      position: [-20, 0, -3.5],
      radius: 4,
      objective: 'Starting position — forward facing',
      instruction: 'Stop here and prepare to reverse. Check behind you first!',
      completed: false,
      instructorMessage: 'Stop here. Now: select REVERSE gear. Look over your right shoulder. Ready?',
    },
    {
      id: 'RV_GEAR',
      position: [-20, 0, -5],
      radius: 2,
      objective: 'Engage reverse gear',
      instruction: 'Clutch in, select R gear, check mirrors and over shoulder.',
      completed: false,
      instructorMessage: 'R gear engaged! Now SLOWLY release clutch. Reverse gently.',
    },
    {
      id: 'RV_STRAIGHT',
      position: [-20, 0, -7],
      radius: 3,
      objective: 'Reverse in straight line',
      instruction: 'Keep steering straight and reverse slowly. Watch your mirrors!',
      completed: false,
      instructorMessage: 'Straight reverse! Keep the wheel straight. Look back and at mirrors.',
    },
    {
      id: 'RV_CORNER',
      position: [-15, 0, -7],
      radius: 3,
      objective: 'Reverse around corner',
      instruction: 'Turn the wheel and reverse around the corner. Remember: steering is inverted!',
      completed: false,
      instructorMessage: 'Corner! Turn wheel LEFT to go RIGHT when reversing. It\'s the opposite!',
    },
    {
      id: 'RV_FINISH',
      position: [-15, 0, -3.5],
      radius: 3,
      objective: 'Stop at target — reverse complete!',
      instruction: 'Stop precisely at the target. Engage handbrake and neutral.',
      completed: false,
      instructorMessage: 'PERFECT reverse! You handled straight line AND corner reversing. Well done!',
    },
  ],
};

// ─── Scenario 5: Parking Between Two Cars ──────────────────

export const LOWPOLY_BETWEEN_PARKING: ScenarioConfig = {
  id: 'lowpoly_between_parking',
  title: 'Park Between Two Cars',
  titleRW: 'Hagarika Hagati y\'Imodoka',
  description: 'Drive forward and park your car precisely between two parked vehicles. Precision is key!',
  descriptionRW: 'Jya imbere kandi uhagaritse imodoka yawe neza hagati y\'imodoka ebyiri.',
  difficulty: 'BEGINNER',
  location: 'Low Poly City — Parking Lot',
  locationRW: 'Low Poly City — Ahantu h\'Imodoka',
  estimatedTime: '2-4 min',
  maxSpeed: 10,
  speedLimit: 8,
  xpReward: 200,
  trainingMode: true,
  objectives: [
    { id: 'approach', text: 'Approach the parking spot slowly', textRW: 'Jya buhoro igerero', icon: '🚗' },
    { id: 'align', text: 'Align with the parking space', textRW: 'Itegura neza', icon: '📍' },
    { id: 'drive_in', text: 'Drive into the space', textRW: 'Injira mu buriri', icon: '⬆️' },
    { id: 'center', text: 'Center between both cars', textRW: 'Itegura hagati', icon: '🎯' },
    { id: 'stop', text: 'Come to a complete stop', textRW: 'Hagarika neza', icon: '🛑' },
  ],
  waypoints: [
    {
      id: 'PK_APPROACH',
      position: [-22, 0, -7],
      radius: 4,
      objective: 'Approach the parking area',
      instruction: 'Drive slowly toward the parking area. Two cars are parked ahead.',
      completed: false,
      instructorMessage: 'Parking lot ahead. See the two cars with a space between them? That\'s your target!',
    },
    {
      id: 'PK_ALIGN',
      position: [-12, 0, -7],
      radius: 3,
      objective: 'Align with the parking space',
      instruction: 'Position yourself alongside the parking space. Get ready to steer in.',
      completed: false,
      instructorMessage: 'Stop here. Your right mirror should be level with the front car\'s rear bumper.',
    },
    {
      id: 'PK_DRIVE_IN',
      position: [-12, 0, -5],
      radius: 2,
      objective: 'Drive into the parking space',
      instruction: 'Turn right and drive slowly into the parking space.',
      completed: false,
      instructorMessage: 'Turn right and drive in! Use small steering inputs. Go very slowly.',
    },
    {
      id: 'PK_CENTER',
      position: [-12, 0, -3.5],
      radius: 2,
      objective: 'Center between the two cars',
      instruction: 'Straighten the wheel and center yourself between both vehicles.',
      completed: false,
      instructorMessage: 'Straighten the wheel! Check both mirrors — equal space on both sides.',
    },
    {
      id: 'PK_COMPLETE',
      position: [-12, 0, -2],
      radius: 2,
      objective: 'Park complete — handbrake on!',
      instruction: 'Come to a stop. Handbrake on, neutral gear. You parked perfectly!',
      completed: false,
      instructorMessage: 'PARKED! Handbrake on, neutral gear. Perfect spacing on both sides!',
    },
  ],
};

// ─── Scenario 6: Stop & Go ─────────────────────────────────

export const LOWPOLY_STOP_AND_GO: ScenarioConfig = {
  id: 'lowpoly_stop_and_go',
  title: 'Stop & Go Driving',
  titleRW: 'Hagarika No Gutangira',
  description: 'Practice stopping and starting at intersections, stop signs, and behind traffic. Essential city driving skill!',
  descriptionRW: 'Jya mu gihe uhagarika no utangira. Ubumenyi bukwiye mu mujyi!',
  difficulty: 'BEGINNER',
  location: 'Low Poly City — Main Avenue',
  locationRW: 'Low Poly City — Umuhanda Mukuru',
  estimatedTime: '2-4 min',
  maxSpeed: 30,
  speedLimit: 25,
  xpReward: 200,
  trainingMode: true,
  objectives: [
    { id: 'stop_sign', text: 'Stop at stop sign', textRW: 'Hagarika ku ibimenyetso', icon: '🛑' },
    { id: 'smooth_start', text: 'Start smoothly after stop', textRW: 'Tangira neza', icon: '🚗' },
    { id: 'behind_traffic', text: 'Stop behind other vehicles', textRW: 'Hagarika inyuma y\'izindi', icon: '🚙' },
    { id: 'no_stall', text: 'Do not stall the engine', textRW: 'Ntukarangize injini', icon: '⚡' },
  ],
  waypoints: [
    {
      id: 'SGO_START',
      position: [-22, 0, -3.5],
      radius: 4,
      objective: 'Start driving on the avenue',
      instruction: 'Begin driving on the main avenue. A stop sign is ahead.',
      completed: false,
      instructorMessage: 'Start driving! Smooth acceleration. There\'s a stop sign coming up.',
    },
    {
      id: 'SGO_STOP_1',
      position: [-12, 0, -3.5],
      radius: 3,
      objective: 'Stop at the stop sign',
      instruction: 'STOP sign ahead! Come to a complete stop behind the line.',
      completed: false,
      instructorMessage: 'STOP SIGN! Full stop. Don\'t just slow down — STOP completely!',
    },
    {
      id: 'SGO_GO_1',
      position: [-12, 0, -7],
      radius: 3,
      objective: 'Start moving after stop',
      instruction: 'Check left-right-left. When clear, start driving again smoothly.',
      completed: false,
      instructorMessage: 'Clear? Go! Smooth start — no stalling. Gentle clutch and throttle.',
    },
    {
      id: 'SGO_BEHIND',
      position: [-2, 0, -7],
      radius: 3,
      objective: 'Stop behind the car ahead',
      instruction: 'Car ahead is stopped! Stop behind it with a safe gap.',
      completed: false,
      instructorMessage: 'Car stopped ahead! Brake gently. Leave enough space to see their rear tires.',
    },
    {
      id: 'SGO_FINAL',
      position: [3, 0, -7],
      radius: 4,
      objective: 'Stop & Go course complete!',
      instruction: 'One more smooth stop and you are done!',
      completed: false,
      instructorMessage: 'STOP! And... that\'s it! You mastered stop-and-go driving. Excellent control!',
    },
  ],
};
